// Generated by packages/engine/scripts/gen-constants.ts. Do not edit by hand.
import type { ParamMeta, PhysicalConstantMeta, SimParams } from "./types";

export const PHYSICAL_CONSTANTS = {
  "F": {
    "value": 96485.33,
    "unit": "C/mol",
    "kind": "physical",
    "description": "Faraday constant",
    "source": "CODATA 2022"
  },
  "R": {
    "value": 8.31446,
    "unit": "J/(mol*K)",
    "kind": "physical",
    "description": "Universal gas constant",
    "source": "CODATA 2022"
  },
  "sigma": {
    "value": 5.670374e-8,
    "unit": "W/(m^2*K^4)",
    "kind": "physical",
    "description": "Stefan-Boltzmann constant",
    "source": "CODATA 2022"
  },
  "gL": {
    "value": 1.62,
    "unit": "m/s^2",
    "kind": "physical",
    "description": "Lunar surface gravity",
    "source": "NASA lunar fact sheet"
  },
  "g0": {
    "value": 9.81,
    "unit": "m/s^2",
    "kind": "physical",
    "description": "Earth standard gravity",
    "source": "standard gravity"
  },
  "ISOLAR": {
    "value": 1361,
    "unit": "W/m^2",
    "kind": "physical",
    "description": "Solar constant at 1 AU",
    "source": "NASA solar irradiance"
  },
  "M_O2": {
    "value": 0.032,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of oxygen",
    "source": "std molar mass"
  },
  "M_H2": {
    "value": 0.002,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of hydrogen",
    "source": "std molar mass"
  },
  "M_H2O": {
    "value": 0.018,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of water",
    "source": "std molar mass"
  },
  "M_CH4": {
    "value": 0.016,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of methane",
    "source": "std molar mass"
  },
  "M_CO2": {
    "value": 0.044,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of carbon dioxide",
    "source": "std molar mass"
  },
  "M_SiO2": {
    "value": 0.0600843,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of silica",
    "source": "std molar mass"
  },
  "M_TiO2": {
    "value": 0.079866,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of titanium dioxide",
    "source": "std molar mass"
  },
  "M_Al2O3": {
    "value": 0.1019613,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of alumina",
    "source": "std molar mass"
  },
  "M_FeO": {
    "value": 0.071844,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of iron(II) oxide",
    "source": "std molar mass"
  },
  "M_MgO": {
    "value": 0.0403044,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of magnesium oxide",
    "source": "std molar mass"
  },
  "M_CaO": {
    "value": 0.0560774,
    "unit": "kg/mol",
    "kind": "physical",
    "description": "Molar mass of calcium oxide",
    "source": "std molar mass"
  },
  "oxideEllinghamSiO2A": {
    "value": -901280,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "SiO2 Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamSiO2B": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "SiO2 Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamTiO2A": {
    "value": -785407,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "TiO2 Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamTiO2B": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "TiO2 Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamAl2O3A": {
    "value": -1132921,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "Al2O3 Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamAl2O3B": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "Al2O3 Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamFeOA": {
    "value": -630988,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "FeO Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamFeOB": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "FeO Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamMgOA": {
    "value": -1248286,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "MgO Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamMgOB": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "MgO Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamCaOA": {
    "value": -1344771,
    "unit": "J/mol-O2",
    "kind": "physical",
    "description": "CaO Ellingham intercept",
    "source": "JANAF fit; V2 cal"
  },
  "oxideEllinghamCaOB": {
    "value": 100,
    "unit": "J/(mol-O2*K)",
    "kind": "physical",
    "description": "CaO Ellingham slope",
    "source": "JANAF fit; V2 cal"
  },
  "oxideRecoveryCalibration": {
    "value": 1.0610956095280686,
    "unit": "1",
    "kind": "physical",
    "description": "V2 recovery scalar for v1 0.225 O2 yield",
    "source": "V2 continuity cal"
  },
  "cpRegMaierA": {
    "value": 700,
    "unit": "J/(kg*K)",
    "kind": "physical",
    "description": "Maier-Kelley constant term",
    "source": "Hemingway-Hayne fit"
  },
  "cpRegMaierB": {
    "value": 0.31559114460668863,
    "unit": "J/(kg*K^2)",
    "kind": "physical",
    "description": "Maier-Kelley linear term",
    "source": "Hemingway-Hayne fit"
  },
  "cpRegMaierC": {
    "value": 0,
    "unit": "J*K/kg",
    "kind": "physical",
    "description": "Maier-Kelley inverse-square term",
    "source": "Hemingway-Hayne fit"
  },
  "dHsub_ice": {
    "value": 2830000,
    "unit": "J/kg",
    "kind": "physical",
    "description": "Sublimation enthalpy of water ice",
    "source": "engineering reference value"
  },
  "dHvap_LOX": {
    "value": 213000,
    "unit": "J/kg",
    "kind": "physical",
    "description": "Latent heat of vaporization of liquid oxygen",
    "source": "engineering reference value"
  },
  "dHvap_LH2": {
    "value": 446000,
    "unit": "J/kg",
    "kind": "physical",
    "description": "Latent heat of vaporization of liquid hydrogen",
    "source": "engineering reference value"
  },
  "dH_sabatier": {
    "value": -165000,
    "unit": "J/mol",
    "kind": "physical",
    "description": "Sabatier reaction enthalpy",
    "source": "standard reaction thermodynamics"
  },
  "dS_sabatier": {
    "value": -173.6,
    "unit": "J/(mol*K)",
    "kind": "physical",
    "description": "Sabatier reaction entropy",
    "source": "standard reaction thermodynamics"
  },
  "tDay": {
    "value": 354,
    "unit": "h",
    "kind": "physical",
    "description": "Approximate lunar daylight duration",
    "source": "lunar synodic period"
  },
  "tNight": {
    "value": 354,
    "unit": "h",
    "kind": "physical",
    "description": "Approximate lunar night duration",
    "source": "lunar synodic period"
  }
} as const satisfies Record<string, PhysicalConstantMeta>;

export const PARAM_META = {
  "site": {
    "value": "equatorial",
    "unit": "mode",
    "kind": "parameter",
    "group": "global",
    "description": "ISRU site mode",
    "source": "model switch"
  },
  "targetKgPerDay": {
    "value": 1000,
    "min": 10,
    "max": 20000,
    "unit": "kg/day",
    "kind": "parameter",
    "group": "global",
    "description": "Daily product target",
    "source": "spec"
  },
  "missionYears": {
    "value": 5,
    "min": 1,
    "max": 20,
    "unit": "yr",
    "kind": "parameter",
    "group": "global",
    "description": "Mission lifetime",
    "source": "spec"
  },
  "enableSabatier": {
    "value": false,
    "unit": "bool",
    "kind": "parameter",
    "group": "global",
    "description": "Enable Sabatier loop",
    "source": "spec"
  },
  "rhoReg": {
    "value": 1800,
    "min": 1300,
    "max": 2200,
    "unit": "kg/m^3",
    "kind": "parameter",
    "group": "excavation",
    "description": "Bulk density of lunar regolith",
    "source": "lunar regolith engineering estimates"
  },
  "c": {
    "value": 500,
    "min": 100,
    "max": 3000,
    "unit": "Pa",
    "kind": "parameter",
    "group": "excavation",
    "description": "Regolith cohesion",
    "source": "lunar soil mechanics literature"
  },
  "Nc": {
    "value": 46.12,
    "min": 1,
    "max": 100,
    "unit": "1",
    "kind": "parameter",
    "group": "excavation",
    "description": "Terzaghi Nc",
    "source": "Terzaghi-McKyes approximation"
  },
  "Nq": {
    "value": 33.3,
    "min": 1,
    "max": 100,
    "unit": "1",
    "kind": "parameter",
    "group": "excavation",
    "description": "Terzaghi Nq",
    "source": "Terzaghi-McKyes approximation"
  },
  "Ngamma": {
    "value": 48.03,
    "min": 1,
    "max": 100,
    "unit": "1",
    "kind": "parameter",
    "group": "excavation",
    "description": "Terzaghi Ngamma",
    "source": "Terzaghi-McKyes approximation"
  },
  "zDepth": {
    "value": 0.1,
    "min": 0.02,
    "max": 0.5,
    "unit": "m",
    "kind": "parameter",
    "group": "excavation",
    "description": "Cut depth",
    "source": "spec"
  },
  "wBlade": {
    "value": 0.5,
    "min": 0.1,
    "max": 2,
    "unit": "m",
    "kind": "parameter",
    "group": "excavation",
    "description": "Excavator blade width",
    "source": "spec"
  },
  "dBlade": {
    "value": 0.1,
    "min": 0.02,
    "max": 0.3,
    "unit": "m",
    "kind": "parameter",
    "group": "excavation",
    "description": "Excavator blade depth",
    "source": "spec"
  },
  "vCut": {
    "value": 0.05,
    "min": 0.01,
    "max": 0.5,
    "unit": "m/s",
    "kind": "parameter",
    "group": "excavation",
    "description": "Cutting velocity",
    "source": "spec"
  },
  "etaDrive": {
    "value": 0.6,
    "min": 0.3,
    "max": 0.95,
    "unit": "1",
    "kind": "parameter",
    "group": "excavation",
    "description": "Drive-train efficiency",
    "source": "spec"
  },
  "eMining": {
    "value": 120000,
    "min": 20000,
    "max": 500000,
    "unit": "J/kg-regolith",
    "kind": "parameter",
    "group": "excavation",
    "description": "Fleet-level specific mining energy",
    "source": "NASA RASSOR-class fleet-level estimate"
  },
  "kExcFleet": {
    "value": 8.5,
    "min": 2,
    "max": 30,
    "unit": "kg/(kg/day)",
    "kind": "parameter",
    "group": "excavation",
    "description": "Excavation fleet mass coefficient",
    "source": "spec"
  },
  "chiIce": {
    "value": 0.05,
    "min": 0.005,
    "max": 0.12,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "thermal",
    "description": "Mass fraction of water ice in polar feedstock",
    "source": "spec"
  },
  "cpRegCold": {
    "value": 800,
    "min": 400,
    "max": 1200,
    "unit": "J/(kg*K)",
    "kind": "parameter",
    "group": "thermal",
    "description": "Cold-regime regolith heat capacity",
    "source": "spec"
  },
  "Tpsr": {
    "value": 40,
    "min": 25,
    "max": 110,
    "unit": "K",
    "kind": "parameter",
    "group": "thermal",
    "description": "Permanently shadowed region temperature",
    "source": "spec"
  },
  "Tsub": {
    "value": 263,
    "min": 200,
    "max": 280,
    "unit": "K",
    "kind": "parameter",
    "group": "thermal",
    "description": "Sublimation operating temperature",
    "source": "spec"
  },
  "kc": {
    "value": 0.0012,
    "min": 0.0001,
    "max": 0.01,
    "unit": "W/(m*K)",
    "kind": "parameter",
    "group": "thermal",
    "description": "Solid-contact conductivity term",
    "source": "spec"
  },
  "kr": {
    "value": 2e-11,
    "min": 1e-12,
    "max": 1e-10,
    "unit": "W/(m*K^4)",
    "kind": "parameter",
    "group": "thermal",
    "description": "Radiative conductivity coefficient",
    "source": "spec"
  },
  "rPore": {
    "value": 0.000005,
    "min": 1e-7,
    "max": 0.0001,
    "unit": "m",
    "kind": "parameter",
    "group": "thermal",
    "description": "Representative pore radius for Knudsen diffusion",
    "source": "spec"
  },
  "Vcell": {
    "value": 4.2,
    "min": 3.5,
    "max": 5,
    "unit": "V",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "MRE operating cell voltage",
    "source": "Sibille et al., MRE parametric sizing"
  },
  "etaCurrent": {
    "value": 0.9,
    "min": 0.5,
    "max": 0.99,
    "unit": "1",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Current efficiency",
    "source": "spec"
  },
  "xO2": {
    "value": 0.45,
    "min": 0.35,
    "max": 0.5,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Oxygen mass fraction in feed regolith",
    "source": "spec"
  },
  "fExtract": {
    "value": 0.5,
    "min": 0.2,
    "max": 0.9,
    "unit": "1",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Extracted fraction of feedstock oxygen",
    "source": "spec"
  },
  "oxideModel": {
    "value": true,
    "unit": "bool",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Use V2 oxide yield model",
    "source": "V2 spec A.1"
  },
  "oxideSiO2": {
    "value": 0.45,
    "min": 0,
    "max": 0.8,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "SiO2 mass fraction",
    "source": "Taylor mare vector"
  },
  "oxideTiO2": {
    "value": 0.04,
    "min": 0,
    "max": 0.2,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "TiO2 mass fraction",
    "source": "Taylor mare vector"
  },
  "oxideAl2O3": {
    "value": 0.13,
    "min": 0,
    "max": 0.4,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Al2O3 mass fraction",
    "source": "Taylor mare vector"
  },
  "oxideFeO": {
    "value": 0.18,
    "min": 0,
    "max": 0.4,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "FeO mass fraction",
    "source": "Taylor mare vector"
  },
  "oxideMgO": {
    "value": 0.09,
    "min": 0,
    "max": 0.3,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "MgO mass fraction",
    "source": "Taylor mare vector"
  },
  "oxideCaO": {
    "value": 0.11,
    "min": 0,
    "max": 0.3,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "CaO mass fraction",
    "source": "Taylor mare vector"
  },
  "cpRegMelt": {
    "value": 1035,
    "min": 800,
    "max": 1600,
    "unit": "J/(kg*K)",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Cp(T) melt scale factor",
    "source": "spec; V2 Cp anchor"
  },
  "Tmelt": {
    "value": 1873,
    "min": 1700,
    "max": 2100,
    "unit": "K",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Molten regolith electrolysis operating temperature",
    "source": "spec"
  },
  "Tambient": {
    "value": 250,
    "min": 100,
    "max": 400,
    "unit": "K",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Feedstock initial ambient temperature",
    "source": "spec"
  },
  "dHfus": {
    "value": 420000,
    "min": 200000,
    "max": 600000,
    "unit": "J/kg",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Regolith fusion enthalpy",
    "source": "spec"
  },
  "fParasitic": {
    "value": 0.225,
    "min": 0.05,
    "max": 0.5,
    "unit": "1",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Radiative and standby parasitic fraction",
    "source": "spec"
  },
  "Amu": {
    "value": 0.00008,
    "min": 0.000001,
    "max": 0.001,
    "unit": "Pa*s/K",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "VFT viscosity coefficient",
    "source": "spec"
  },
  "Bmu": {
    "value": 6000,
    "min": 2000,
    "max": 12000,
    "unit": "K",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "VFT viscosity activation coefficient",
    "source": "spec"
  },
  "T0vft": {
    "value": 800,
    "min": 400,
    "max": 1200,
    "unit": "K",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "VFT reference temperature",
    "source": "spec"
  },
  "rhoSlag": {
    "value": 3000,
    "min": 2500,
    "max": 3400,
    "unit": "kg/m^3",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Molten slag density",
    "source": "spec"
  },
  "hMelt": {
    "value": 0.2,
    "min": 0.05,
    "max": 1,
    "unit": "m",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Characteristic melt height for drain velocity",
    "source": "spec"
  },
  "thetaDrain": {
    "value": 0.26,
    "min": 0.05,
    "max": 1,
    "unit": "rad",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Drain slope angle",
    "source": "spec"
  },
  "Dox": {
    "value": 5e-10,
    "min": 1e-11,
    "max": 1e-8,
    "unit": "m^2/s",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Oxygen ion diffusivity",
    "source": "spec"
  },
  "Cbulk": {
    "value": 10000,
    "min": 1000,
    "max": 50000,
    "unit": "mol/m^3",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Bulk oxygen ion concentration",
    "source": "spec"
  },
  "deltaDiff": {
    "value": 0.001,
    "min": 0.0001,
    "max": 0.01,
    "unit": "m",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Diffusion boundary-layer thickness",
    "source": "spec"
  },
  "jOperating": {
    "value": 1200,
    "min": 100,
    "max": 10000,
    "unit": "A/m^2",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "Operating current density",
    "source": "spec"
  },
  "kReactorMass": {
    "value": 12,
    "min": 3,
    "max": 40,
    "unit": "kg/(kg/day)",
    "kind": "parameter",
    "group": "electrolysis",
    "description": "MRE reactor/plant mass coefficient",
    "source": "spec"
  },
  "Vel": {
    "value": 1.8,
    "min": 1.5,
    "max": 2.5,
    "unit": "V",
    "kind": "parameter",
    "group": "sabatier",
    "description": "Water electrolysis cell voltage",
    "source": "spec"
  },
  "etaFaradayEl": {
    "value": 0.95,
    "min": 0.7,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "sabatier",
    "description": "Faradaic efficiency for water electrolysis",
    "source": "spec"
  },
  "fConversion": {
    "value": 0.95,
    "min": 0.5,
    "max": 0.999,
    "unit": "1",
    "kind": "parameter",
    "group": "sabatier",
    "description": "Sabatier conversion fraction",
    "source": "spec"
  },
  "Tsabatier": {
    "value": 623,
    "min": 523,
    "max": 723,
    "unit": "K",
    "kind": "parameter",
    "group": "sabatier",
    "description": "Sabatier reactor temperature",
    "source": "spec"
  },
  "reserveDays": {
    "value": 30,
    "min": 5,
    "max": 120,
    "unit": "day",
    "kind": "parameter",
    "group": "cryo",
    "description": "Cryogenic storage reserve duration",
    "source": "spec"
  },
  "rhoCryo": {
    "value": 1141,
    "min": 70,
    "max": 1200,
    "unit": "kg/m^3",
    "kind": "parameter",
    "group": "cryo",
    "description": "Cryogenic product density",
    "source": "LOX default"
  },
  "alphaTank": {
    "value": 0.2,
    "min": 0.05,
    "max": 0.9,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "Tank solar absorptivity",
    "source": "spec"
  },
  "epsTank": {
    "value": 0.05,
    "min": 0.02,
    "max": 0.9,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "Tank emissivity",
    "source": "spec"
  },
  "Fview": {
    "value": 0.5,
    "min": 0,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "Surface view factor",
    "source": "spec"
  },
  "Tsurface": {
    "value": 400,
    "min": 40,
    "max": 400,
    "unit": "K",
    "kind": "parameter",
    "group": "cryo",
    "description": "Effective illuminated surface temperature",
    "source": "spec"
  },
  "Ttank": {
    "value": 90,
    "min": 20,
    "max": 120,
    "unit": "K",
    "kind": "parameter",
    "group": "cryo",
    "description": "Tank cold-side temperature",
    "source": "spec"
  },
  "Nmli": {
    "value": 40,
    "min": 5,
    "max": 100,
    "unit": "layers",
    "kind": "parameter",
    "group": "cryo",
    "description": "Number of MLI layers",
    "source": "spec"
  },
  "Nlaydens": {
    "value": 20,
    "min": 5,
    "max": 40,
    "unit": "layers/cm",
    "kind": "parameter",
    "group": "cryo",
    "description": "MLI layer density",
    "source": "spec"
  },
  "C1mli": {
    "value": 0.00024,
    "min": 0.00024,
    "max": 0.00024,
    "unit": "correlation",
    "kind": "parameter",
    "group": "cryo",
    "description": "Lockheed MLI solid-conduction coefficient",
    "source": "Lockheed MLI correlation"
  },
  "rExp": {
    "value": 2.63,
    "min": 2.63,
    "max": 2.63,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "Lockheed MLI layer-density exponent",
    "source": "Lockheed MLI correlation"
  },
  "C2mli": {
    "value": 4.944e-10,
    "min": 4.944e-10,
    "max": 4.944e-10,
    "unit": "correlation",
    "kind": "parameter",
    "group": "cryo",
    "description": "Lockheed MLI radiation coefficient",
    "source": "Lockheed MLI correlation"
  },
  "epsLayer": {
    "value": 0.031,
    "min": 0.01,
    "max": 0.1,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "MLI layer emissivity",
    "source": "spec"
  },
  "qStrutW": {
    "value": 5,
    "min": 0,
    "max": 100,
    "unit": "W",
    "kind": "parameter",
    "group": "cryo",
    "description": "Conductive heat leak through tank supports",
    "source": "spec"
  },
  "eta2ndLaw": {
    "value": 0.2,
    "min": 0.05,
    "max": 0.4,
    "unit": "1",
    "kind": "parameter",
    "group": "cryo",
    "description": "Cryocooler second-law efficiency",
    "source": "spec"
  },
  "secLiquefaction": {
    "value": 2.2,
    "min": 1,
    "max": 4,
    "unit": "kWh/kg",
    "kind": "parameter",
    "group": "cryo",
    "description": "Liquefier specific energy consumption",
    "source": "spec"
  },
  "kCryoMass": {
    "value": 6,
    "min": 2,
    "max": 20,
    "unit": "kg/(kg/day)",
    "kind": "parameter",
    "group": "cryo",
    "description": "Cryogenic block mass coefficient",
    "source": "spec"
  },
  "etaWire": {
    "value": 0.95,
    "min": 0.8,
    "max": 0.99,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Array-to-load wiring efficiency",
    "source": "spec"
  },
  "etaRoundTrip": {
    "value": 0.6,
    "min": 0.3,
    "max": 0.9,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Night storage round-trip efficiency",
    "source": "spec"
  },
  "etaCell": {
    "value": 0.3,
    "min": 0.15,
    "max": 0.45,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Solar cell efficiency",
    "source": "spec"
  },
  "thetaSun": {
    "value": 0.262,
    "min": 0,
    "max": 1.3,
    "unit": "rad",
    "kind": "parameter",
    "group": "power",
    "description": "Solar incidence angle",
    "source": "spec"
  },
  "Fdegrade": {
    "value": 0.85,
    "min": 0.5,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Solar degradation factor",
    "source": "spec"
  },
  "DoD": {
    "value": 0.8,
    "min": 0.3,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Storage depth of discharge",
    "source": "spec"
  },
  "etaDischarge": {
    "value": 0.95,
    "min": 0.7,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Storage discharge efficiency",
    "source": "spec"
  },
  "SEstorage": {
    "value": 600,
    "min": 100,
    "max": 1500,
    "unit": "Wh/kg",
    "kind": "parameter",
    "group": "power",
    "description": "Specific energy of regenerative fuel-cell storage",
    "source": "spec"
  },
  "Rarray": {
    "value": 20,
    "min": 5,
    "max": 60,
    "unit": "kg/kW",
    "kind": "parameter",
    "group": "power",
    "description": "Solar array specific mass",
    "source": "spec"
  },
  "Tsource": {
    "value": 1200,
    "min": 800,
    "max": 1600,
    "unit": "K",
    "kind": "parameter",
    "group": "power",
    "description": "Fission system hot-side temperature",
    "source": "spec"
  },
  "Tsink": {
    "value": 600,
    "min": 300,
    "max": 900,
    "unit": "K",
    "kind": "parameter",
    "group": "power",
    "description": "Fission system sink temperature",
    "source": "spec"
  },
  "Tenv": {
    "value": 250,
    "min": 40,
    "max": 400,
    "unit": "K",
    "kind": "parameter",
    "group": "power",
    "description": "Radiator environment temperature",
    "source": "spec"
  },
  "etaMech": {
    "value": 0.55,
    "min": 0.2,
    "max": 0.8,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Thermal mechanical efficiency",
    "source": "spec"
  },
  "etaRad": {
    "value": 0.85,
    "min": 0.5,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Radiator efficiency",
    "source": "spec"
  },
  "epsRad": {
    "value": 0.85,
    "min": 0.5,
    "max": 0.98,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Radiator emissivity",
    "source": "spec"
  },
  "MshieldKg": {
    "value": 1500,
    "min": 500,
    "max": 8000,
    "unit": "kg",
    "kind": "parameter",
    "group": "power",
    "description": "Nuclear shielding mass",
    "source": "spec"
  },
  "alphaSpecific": {
    "value": 30,
    "min": 8,
    "max": 90,
    "unit": "kg/kW",
    "kind": "parameter",
    "group": "power",
    "description": "Fission system specific mass excluding shielding",
    "source": "spec"
  },
  "dSolar": {
    "value": 0.05,
    "min": 0.005,
    "max": 0.2,
    "unit": "1/yr",
    "kind": "parameter",
    "group": "power",
    "description": "Solar degradation per year",
    "source": "spec"
  },
  "dNuclear": {
    "value": 0.01,
    "min": 0.001,
    "max": 0.05,
    "unit": "1/yr",
    "kind": "parameter",
    "group": "power",
    "description": "Annual nuclear mass-growth/maintenance factor",
    "source": "spec"
  },
  "w0Beam": {
    "value": 0.05,
    "min": 0.05,
    "max": 0.05,
    "unit": "m",
    "kind": "parameter",
    "group": "power",
    "description": "Initial beam waist",
    "source": "spec"
  },
  "thetaDivBeam": {
    "value": 0.000005,
    "min": 0.000001,
    "max": 0.0001,
    "unit": "rad",
    "kind": "parameter",
    "group": "power",
    "description": "Beam divergence angle",
    "source": "spec"
  },
  "zCraterDrop": {
    "value": 4200,
    "min": 500,
    "max": 6000,
    "unit": "m",
    "kind": "parameter",
    "group": "power",
    "description": "Rim-to-floor crater drop for beamed power",
    "source": "spec"
  },
  "rReceiver": {
    "value": 0.5,
    "min": 0.1,
    "max": 5,
    "unit": "m",
    "kind": "parameter",
    "group": "power",
    "description": "Receiver radius for beamed power capture",
    "source": "spec"
  },
  "etaEmitter": {
    "value": 0.5,
    "min": 0.2,
    "max": 0.8,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Beam emitter efficiency",
    "source": "spec"
  },
  "etaPvReceiver": {
    "value": 0.5,
    "min": 0.3,
    "max": 0.7,
    "unit": "1",
    "kind": "parameter",
    "group": "power",
    "description": "Beam receiver photovoltaic efficiency",
    "source": "spec"
  },
  "M0leo": {
    "value": 1100000,
    "min": 500000,
    "max": 2000000,
    "unit": "kg",
    "kind": "parameter",
    "group": "logistics",
    "description": "Initial mass in low Earth orbit",
    "source": "spec"
  },
  "dvTotal": {
    "value": 5900,
    "min": 5500,
    "max": 6500,
    "unit": "m/s",
    "kind": "parameter",
    "group": "logistics",
    "description": "Total delivery delta-v",
    "source": "spec"
  },
  "IspLander": {
    "value": 380,
    "min": 310,
    "max": 450,
    "unit": "s",
    "kind": "parameter",
    "group": "logistics",
    "description": "Landing stage specific impulse",
    "source": "spec"
  },
  "MdryLander": {
    "value": 120000,
    "min": 60000,
    "max": 200000,
    "unit": "kg",
    "kind": "parameter",
    "group": "logistics",
    "description": "Dry lander mass",
    "source": "spec"
  },
  "MresidProp": {
    "value": 5000,
    "min": 0,
    "max": 20000,
    "unit": "kg",
    "kind": "parameter",
    "group": "logistics",
    "description": "Residual propellant mass",
    "source": "spec"
  },
  "etaPack": {
    "value": 0.85,
    "min": 0.6,
    "max": 1,
    "unit": "1",
    "kind": "parameter",
    "group": "logistics",
    "description": "Payload packing factor",
    "source": "spec"
  },
  "gearRatio": {
    "value": 6,
    "min": 2,
    "max": 15,
    "unit": "kg/kg",
    "kind": "parameter",
    "group": "logistics",
    "description": "Earth launch mass saved per kg product",
    "source": "spec"
  },
  "Pinternal": {
    "value": 101325,
    "min": 50000,
    "max": 101325,
    "unit": "Pa",
    "kind": "parameter",
    "group": "construction",
    "description": "Habitat internal pressure for full pressure balance",
    "source": "spec"
  },
  "Eslag": {
    "value": 80000000000,
    "min": 60000000000,
    "max": 90000000000,
    "unit": "Pa",
    "kind": "parameter",
    "group": "construction",
    "description": "Slag elastic modulus",
    "source": "spec"
  },
  "alphaCte": {
    "value": 0.000007,
    "min": 0.000004,
    "max": 0.00001,
    "unit": "1/K",
    "kind": "parameter",
    "group": "construction",
    "description": "Slag coefficient of thermal expansion",
    "source": "spec"
  },
  "nu": {
    "value": 0.25,
    "min": 0.15,
    "max": 0.35,
    "unit": "1",
    "kind": "parameter",
    "group": "construction",
    "description": "Slag Poisson ratio",
    "source": "spec"
  },
  "sigmaTensile": {
    "value": 30000000,
    "min": 10000000,
    "max": 60000000,
    "unit": "Pa",
    "kind": "parameter",
    "group": "construction",
    "description": "Slag tensile strength",
    "source": "spec"
  },
  "rhoGasPlume": {
    "value": 0.01,
    "min": 0.001,
    "max": 0.1,
    "unit": "kg/m^3",
    "kind": "parameter",
    "group": "construction",
    "description": "Exhaust plume gas density at pad",
    "source": "spec"
  },
  "vGasPlume": {
    "value": 3000,
    "min": 1000,
    "max": 4000,
    "unit": "m/s",
    "kind": "parameter",
    "group": "construction",
    "description": "Exhaust plume velocity",
    "source": "spec"
  },
  "Cf": {
    "value": 0.005,
    "min": 0.001,
    "max": 0.02,
    "unit": "1",
    "kind": "parameter",
    "group": "construction",
    "description": "Plume shear coefficient",
    "source": "spec"
  },
  "tauAllowable": {
    "value": 20000000,
    "min": 5000000,
    "max": 50000000,
    "unit": "Pa",
    "kind": "parameter",
    "group": "construction",
    "description": "Allowable pad shear stress",
    "source": "spec"
  },
  "FS": {
    "value": 2,
    "min": 1.2,
    "max": 4,
    "unit": "1",
    "kind": "parameter",
    "group": "construction",
    "description": "Pad shear factor of safety",
    "source": "spec"
  },
  "dPad": {
    "value": 30,
    "min": 10,
    "max": 60,
    "unit": "m",
    "kind": "parameter",
    "group": "construction",
    "description": "Landing pad diameter",
    "source": "spec"
  },
  "tPad": {
    "value": 0.3,
    "min": 0.1,
    "max": 1,
    "unit": "m",
    "kind": "parameter",
    "group": "construction",
    "description": "Landing pad thickness",
    "source": "spec"
  },
  "shieldDesignM": {
    "value": 2.5,
    "min": 0.5,
    "max": 21,
    "unit": "m",
    "kind": "parameter",
    "group": "construction",
    "description": "Design shielding depth",
    "source": "spec"
  },
  "areaHabRoof": {
    "value": 200,
    "min": 50,
    "max": 1000,
    "unit": "m^2",
    "kind": "parameter",
    "group": "construction",
    "description": "Habitat roof area to shield",
    "source": "spec"
  },
  "fDistill": {
    "value": 0.1,
    "min": 0,
    "max": 0.5,
    "unit": "1",
    "kind": "parameter",
    "group": "thermal",
    "description": "Distillation overhead fraction",
    "source": "energy Sankey spec"
  },
  "castDeltaT": {
    "value": 30,
    "min": 5,
    "max": 200,
    "unit": "K",
    "kind": "parameter",
    "group": "construction",
    "description": "Slag cooling delta",
    "source": "warning acceptance spec"
  }
} as const satisfies Record<keyof SimParams, ParamMeta>;

export const DEFAULTS = {
  "site": "equatorial",
  "targetKgPerDay": 1000,
  "missionYears": 5,
  "enableSabatier": false,
  "rhoReg": 1800,
  "c": 500,
  "Nc": 46.12,
  "Nq": 33.3,
  "Ngamma": 48.03,
  "zDepth": 0.1,
  "wBlade": 0.5,
  "dBlade": 0.1,
  "vCut": 0.05,
  "etaDrive": 0.6,
  "eMining": 120000,
  "kExcFleet": 8.5,
  "chiIce": 0.05,
  "cpRegCold": 800,
  "Tpsr": 40,
  "Tsub": 263,
  "kc": 0.0012,
  "kr": 2e-11,
  "rPore": 0.000005,
  "Vcell": 4.2,
  "etaCurrent": 0.9,
  "xO2": 0.45,
  "fExtract": 0.5,
  "oxideModel": true,
  "oxideSiO2": 0.45,
  "oxideTiO2": 0.04,
  "oxideAl2O3": 0.13,
  "oxideFeO": 0.18,
  "oxideMgO": 0.09,
  "oxideCaO": 0.11,
  "cpRegMelt": 1035,
  "Tmelt": 1873,
  "Tambient": 250,
  "dHfus": 420000,
  "fParasitic": 0.225,
  "Amu": 0.00008,
  "Bmu": 6000,
  "T0vft": 800,
  "rhoSlag": 3000,
  "hMelt": 0.2,
  "thetaDrain": 0.26,
  "Dox": 5e-10,
  "Cbulk": 10000,
  "deltaDiff": 0.001,
  "jOperating": 1200,
  "kReactorMass": 12,
  "Vel": 1.8,
  "etaFaradayEl": 0.95,
  "fConversion": 0.95,
  "Tsabatier": 623,
  "reserveDays": 30,
  "rhoCryo": 1141,
  "alphaTank": 0.2,
  "epsTank": 0.05,
  "Fview": 0.5,
  "Tsurface": 400,
  "Ttank": 90,
  "Nmli": 40,
  "Nlaydens": 20,
  "C1mli": 0.00024,
  "rExp": 2.63,
  "C2mli": 4.944e-10,
  "epsLayer": 0.031,
  "qStrutW": 5,
  "eta2ndLaw": 0.2,
  "secLiquefaction": 2.2,
  "kCryoMass": 6,
  "etaWire": 0.95,
  "etaRoundTrip": 0.6,
  "etaCell": 0.3,
  "thetaSun": 0.262,
  "Fdegrade": 0.85,
  "DoD": 0.8,
  "etaDischarge": 0.95,
  "SEstorage": 600,
  "Rarray": 20,
  "Tsource": 1200,
  "Tsink": 600,
  "Tenv": 250,
  "etaMech": 0.55,
  "etaRad": 0.85,
  "epsRad": 0.85,
  "MshieldKg": 1500,
  "alphaSpecific": 30,
  "dSolar": 0.05,
  "dNuclear": 0.01,
  "w0Beam": 0.05,
  "thetaDivBeam": 0.000005,
  "zCraterDrop": 4200,
  "rReceiver": 0.5,
  "etaEmitter": 0.5,
  "etaPvReceiver": 0.5,
  "M0leo": 1100000,
  "dvTotal": 5900,
  "IspLander": 380,
  "MdryLander": 120000,
  "MresidProp": 5000,
  "etaPack": 0.85,
  "gearRatio": 6,
  "Pinternal": 101325,
  "Eslag": 80000000000,
  "alphaCte": 0.000007,
  "nu": 0.25,
  "sigmaTensile": 30000000,
  "rhoGasPlume": 0.01,
  "vGasPlume": 3000,
  "Cf": 0.005,
  "tauAllowable": 20000000,
  "FS": 2,
  "dPad": 30,
  "tPad": 0.3,
  "shieldDesignM": 2.5,
  "areaHabRoof": 200,
  "fDistill": 0.1,
  "castDeltaT": 30
} as const satisfies SimParams;
