import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Entry = {
  value: number | string | boolean;
  unit: string;
  kind: "physical" | "parameter";
  min?: number;
  max?: number;
  group?: string;
  description: string;
  source: string;
};

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const constantsPath = resolve(root, "constants/constants.json");
const outPath = resolve(here, "../src/constants.ts");

const raw = JSON.parse(readFileSync(constantsPath, "utf8")) as Record<string, Entry>;
const physical = Object.fromEntries(
  Object.entries(raw).filter(([, entry]) => entry.kind === "physical")
);
const params = Object.fromEntries(
  Object.entries(raw).filter(([, entry]) => entry.kind === "parameter")
);
const defaults = Object.fromEntries(
  Object.entries(params).map(([key, entry]) => [key, entry.value])
);

const source = `// Generated by packages/engine/scripts/gen-constants.ts. Do not edit by hand.
import type { ParamMeta, PhysicalConstantMeta, SimParams } from "./types";

export const PHYSICAL_CONSTANTS = ${JSON.stringify(physical, null, 2)} as const satisfies Record<string, PhysicalConstantMeta>;

export const PARAM_META = ${JSON.stringify(params, null, 2)} as const satisfies Record<keyof SimParams, ParamMeta>;

export const DEFAULTS = ${JSON.stringify(defaults, null, 2)} as const satisfies SimParams;
`;

writeFileSync(outPath, source);
